
package GUI;

import Desecho.Desecho;
import LogicaGUI.MenuPrincipalLog;
import Usuarios.ManejadorArchivoUsuarios;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JPanel;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Josué
 */

public class Estadistica extends javax.swing.JFrame {
	
    private ManejadorArchivoUsuarios fileManager;
	private ArrayList<Desecho> des;
	
	private ButtonGroup grupo = new ButtonGroup();
	private JRadioButton op1 = new JRadioButton("Opción 1");
	private JRadioButton op2 = new JRadioButton("Opción 2");
	private JRadioButton op3 = new JRadioButton("Opción 3");

	private DefaultCategoryDataset datasetgrafica  = new DefaultCategoryDataset();
    
    public Estadistica(ManejadorArchivoUsuarios fileManager, ArrayList<Desecho> des){
        this.fileManager = fileManager;
		this.des = des;
        doMachin();
	}
	private void generardataset(){
		double cantidad = 0d;
		int periodoTiempo = 7;
		int j = 0;

		for(int i = 0; i< periodoTiempo; i++){
			j++;
			for(Desecho d: des){
				System.out.println(i);
			if(!d.isTipoMasa()){
				cantidad = (d.getCantidad() * 1000);
			}else{
				cantidad = d.getCantidad();
			}
			datasetgrafica.addValue(cantidad, d.getCategoria(), "dia: " + j);
				
			}
		}
	}
    private void doMachin() {
        initComponents();
		JPanel panel = new JPanel();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
		int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
		this.setBounds((ancho / 2) - (this.getWidth() / 2),  (alto / 2) - (this.getHeight() / 2),1080 , 720);
		this.setSize(1080, 720);
		grafica.setPreferredSize(new Dimension(100, 100));
		grafica.setMaximumSize(new Dimension(100, 100));
		grafica.setMinimumSize(new Dimension(100, 100));

		this.setMaximumSize(new Dimension(1080, 720));
		this.setPreferredSize(new Dimension(900, 720));
		this.setMinimumSize(new Dimension(900, 720));

		for(Desecho c: des){
			jComboBox1.addItem(c.getCategoria());
		}
		jComboBox1.addItem("Todos");

        grupo.add(op1);
        grupo.add(op2);
        grupo.add(op3);
        panel.add(op1);
        panel.add(op2);
        panel.add(op3);
        getContentPane().add(panel);
        getContentPane().setLayout(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //setSize(300, 120);
		generardataset();
		mostrarGrafica();
        setVisible(true);

		
    }
	private void mostrarGrafica(){
		String periodoTiempo= "este es el periodo de tiempo";

        MenuPrincipalLog mpl = new MenuPrincipalLog();
        grafica.setLayout(new BorderLayout());
           // ChartPanel panel = mpl.generateChart("este es el titulo","prueba","no se que estoy haciendo",periodoTiempo,datasetgrafica);
		   JFreeChart panela = ChartFactory.createBarChart("Basura generada", periodoTiempo, "gramos", datasetgrafica);
		   ChartPanel panel = new ChartPanel(panela);

            //panel.setSize(400, 600);
            grafica.add(panel,0);
            //this.pack();
	}
	


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        grafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafica");
        setBackground(new java.awt.Color(102, 153, 0));
        setForeground(new java.awt.Color(102, 153, 0));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);

        jButton9.setText("Regresar al menú principal");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Informacion referente a la estadistica");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        grafica.setMinimumSize(new java.awt.Dimension(400, 400));
        grafica.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout graficaLayout = new javax.swing.GroupLayout(grafica);
        grafica.setLayout(graficaLayout);
        graficaLayout.setHorizontalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graficaLayout.setVerticalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grafica, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(91, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel grafica;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
